# Data path and active mass (set to 1 if data is normalized with regards to active mass)
files = [
	["./testdata/HV_LNA05MO_E1_AlClad_LP30_C13.mpt","1.0"],
	["./testdata/HV_LNA05MO_E1_SS304_LP30_C11.mpt","1.0"],
	["./testdata/HV_LNA05MO_E1_SS316_LP30_C12.mpt","1.0"],
]

[settings]
percentage = false              # Wether or not to use percentage in capacity vs cycles plot
qcplot = false                   # Wether or not to plot capacity vs cycles
vqplot = true                   # Wether or not to plot voltage versus capacity plot (cycling curves)
dqdvplot = false                # Wether or not to plot dQ/dV plots from the GCPL data
specific_cycles = false         # Will make global limit of cycles, can be range or list of cycles
suptitle = 'Capacity retention' # Title of plot
ylabel = 'Specific capacity [mAh/g]'
xlabel = 'Cycles'
start_cut = 0
all_in_one = true