# Data path and active mass (set to 1 if data is normalized with regards to active mass)
files = [
	#["./testdata/MR_B_057.csv", "1.0"],
	#["./testdata/9_A05LNMO_E1_C3.txt", "0.00687"],
	#["./testdata/9_A05LNMO_E1_C4.txt", "0.00703"],
	#["./testdata/6_LNMO_E1_C2.txt", "0.00579"],
	#["./testdata/6_LNMO_E1_C3.txt", "0.00450"],
	#["./testdata/P2_new.txt", "0.284"],
	#["./testdata/AMR_13_LNA2MO_E1_C1_C14.mpt", "1.00"],
	["./testdata/AMR_15_A2LNMO_E2_C1_C05_reduced.ecdh", "1.00"],
]

[settings]
percentage = false              # Wether or not to use percentage in capacity vs cycles plot
rawplot = false
rawplot_capacity = false        # Wether or not to use cumulative capacity on x-axis
qcplot = false                   # Wether or not to plot capacity vs cycles
vcplot = true                   # Wether or not to plot voltage curves (either CV og GC depending on data)
dqdvplot = false                # Wether or not to plot dQ/dV plots from the GCPL data
specific_cycles = false         # Will make global limit of cycles, can be range or list of cycles
suptitle = 'Capacity retention' # Title of plot
ylabel = 'Specific capacity [mAh/g]'
xlabel = 'Cycles'
start_cut = 0
all_in_one = false
fancyplot = false

[datatreatment]
reduce_data = false             # Reduces large files by changing potential resolution to 10mV and time resolution to 10s (new file is saved at same location as input file)
dt = 20                         # Maximum voltage which goes by unrecorded
dV = 0.02                       # Maximum time which goes by unrecorded
smooth_data = false             # removes outliers, new file saved at same location as input file