# Data path and active mass (set to 1 if data is normalized with regards to active mass)
files = [
    ["./testdata/TiO2_on_Si.mpt", "0.01"],
]

[settings]
percentage = true              # Wether or not to use percentage in capacity vs cycles plot
qcplot = true                   # Wether or not to plot capacity vs cycles
vqplot = true                   # Wether or not to plot voltage versus capacity plot (cycling curves)
dqdvplot = false                # Wether or not to plot dQ/dV plots from the GCPL data
specific_cycles = false         # Will make global limit of cycles, can be range or list of cycles
suptitle = 'Capacity retention' # Title of plot
ylabel = 'Specific capacity [mAh/g]'
xlabel = 'Cycles'