# Data path and active mass (set to 1 if data is normalized with regards to active mass)
files = [
    ["../testdata/8_LA05NMO_E1_C2_RC.dat", "0.01"],
    ["../testdata/RVT_LFCO_75.csv", "0.01"],
]

[settings]
percentage = false              # Wether or not to use percentage in capacity vs cycles plot
qcplot = true                   # Wether or not to plot capacity vs cycles
vqplot = true                   # Wether or not to plot voltage versus capacity plot (cycling curves)
suptitle = 'Capacity retention' # Title of plot
start_cut = 0                   # Number of cycles to cut away from start of data
ylabel = 'Specific capacity [mAh/g]'
xlabel = 'Cycles'